// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroVisitas.WebAPI.Model;

namespace RegistroVisitas.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211105123400_Placas")]
    partial class Placas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("RegistroVisitas.WebAPI.Model.Visita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CasaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraDeEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHoraDeSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDePase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recepcionista")
                        .HasColumnType("TEXT");

                    b.Property<string>("Visitante")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Visitas");
                });
#pragma warning restore 612, 618
        }
    }
}
