// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistroVisitas.WebAPI.Model;

#nullable disable

namespace RegistroVisitas.WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211109052504_Recepcionistas")]
    partial class Recepcionistas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("RegistroVisitas.WebAPI.Model.Recepcionista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nombre", "Codigo");

                    b.ToTable("Recepcionistas");
                });

            modelBuilder.Entity("RegistroVisitas.WebAPI.Model.Sesiones", b =>
                {
                    b.Property<int>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recepcionista")
                        .HasColumnType("TEXT");

                    b.HasKey("Numero");

                    b.HasIndex("Fecha");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("RegistroVisitas.WebAPI.Model.Visita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CasaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaHoraDeEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaHoraDeSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Foto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDePase")
                        .HasColumnType("TEXT");

                    b.Property<string>("Placas")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recepcionista")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecepcionistaDeSalida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Visitante")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaHoraDeEntrada");

                    b.ToTable("Visitas");
                });
#pragma warning restore 612, 618
        }
    }
}
